################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: English
    sections:
      - title: Home
        link: docs/HomepageEditada.md
      - title: Introduction
        link: docs/APIs-Introduction.md
      - title: Token Access
        link: docs/TokenGenerationforWeb-services.md
      - title: Prepayment Info
        link: docs/PrepaymentInformation.md
      - title: Backoffice
        link: docs/BackofficeInformation.md
      - title: Update/Get Merchant Info
        link: docs/UpdateGetMerchantInformation.md
      - title: Boarding
        link: docs/BoardingInformation.md
      - title: Logistic
        link: docs/LogisticInformation.md
      - title: Sales
        link: docs/SalesInformation.md
      - title: Split - Payments
        link: docs/SplitPaymentsInformation.md
      - title: Release notes
        sections:
          - title: March 2022
            link: docs/release-notes/2022/march.md
  - title: Português
    sections:
      - title: Página principal
        link: docs/portugues/HomepageEditada.md
      - title: Introdução
        link: docs/portugues/APIs-Introduction.md
      - title: Acesso a Token
        link: docs/portugues/TokenGenerationforWeb-services.md
      - title: Informações de pré-pagamento
        link: docs/portugues/PrepaymentInformation.md
      - title: Backoffice
        link: docs/portugues/BackofficeInformation.md
      - title: Atualizar/Obter informações dos clientes
        link: docs/portugues/UpdateGetMerchantInformation.md
      - title: Credenciamento
        link: docs/portugues/BoardingInformation.md
      - title: Logística
        link: docs/portugues/LogisticInformation.md
      - title: Vendas
        link: docs/portugues/SalesInformation.md
      - title: Informações de pagamentos divididos
        link: docs/portugues/SplitPaymentsInformation.md
      - title: Release notes
        sections:
          - title: March 2022
            link: docs/release-notes/2022/march.md
  - title: Español
    sections:
      - title: Pagina principal
        link: docs/espanol/HomepageEditada.md
      - title: Introducción
        link: docs/espanol/APIs-Introduction.md
      - title: Acceso a tokens
        link: docs/espanol/TokenGenerationforWeb-services.md
      - title: Información de prepago
        link: docs/espanol/PrepaymentInformation.md
      - title: Backoffice
        link: docs/espanol/BackofficeInformation.md
      - title: Actualizar/Obtener información del cliente
        link: docs/espanol/UpdateGetMerchantInformation.md
      - title: Acreditación
        link: docs/espanol/BoardingInformation.md
      - title: Logística
        link: docs/espanol/LogisticInformation.md
      - title: Ventas
        link: docs/espanol/SalesInformation.md
      - title: Información de pago dividido
        link: docs/espanol/SplitPaymentsInformation.md
      - title: Release notes
        sections:
        - title: March 2022
          link: docs/release-notes/2022/march.md
