################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: LATAM BR - Digital APIs
  productionDescription: "Have access to a complete set of APIs without pain! Find development tools, samples of codes and resources to help you in order to integrate your Apps integrally or partially using Fiserv Platform! Wish to start a new revenue source? Integrate your platform to Fiserv Marketplace, and register merchants to have payments processed directly in your site, and be paid for that!"
  whoIsItFor: Fiserv and Clients
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: Fiserv
featuredFeatures:
  - title: Work with the best!
    description:  Specialized professionals in this industry that will dedicate all the time to understand the complexity of your business.
    tags: ["sba-EN-solicitar-token"]
    bullets: ["sba-EN-solicitar-token" ]
    relatedDocs:
      - relatedDoc: 
        title: APIs - Introduction
        description: APIs - Introduction
        link: ./docs/APIs-Introduction.md
      - relatedDoc: 
        title: Token Access
        description: Token Access
        link: ./docs/TokenGenerationforWeb-services.md
    relatedAPIs:
      - relatedAPI: 
        title: Token Access
        description: Token Access
        type: "post"
        path: "/"
  - title: Open Environment
    description: If you are building a new solution 'all-in-one', looking for a PCI Compliance Solution, enabling EMV or even any other requirement, our platform will save you time, money and resource.
    tags: [ "sba-EN-solicitar-token" ]
    bullets: [ "sba-EN-solicitar-token" ]
    relatedDocs:
      - relatedDoc:
        title: APIs - Introduction
        description: APIs - Introduction
        link: ./docs/APIs-Introduction.md
      - relatedDoc:
        title: Token Access
        description: Token Access
        link: ./docs/TokenGenerationforWeb-services.md
    relatedAPIs:
      - relatedAPI:
        title: Token Access
        description: Token Access
        type: "post"
        path: "/"
  - title: All In One
    description: Create, Test, Certify and Deliver application of payment through only one interface.
    tags: [ "sba-EN-solicitar-token" ]
    bullets: [ "sba-EN-solicitar-token" ]
    relatedDocs:
      - relatedDoc:
        title: APIs - Introduction
        description: APIs - Introduction
        link: ./docs/APIs-Introduction.md
      - relatedDoc:
        title: Token Access
        description: Token Access
        link: ./docs/TokenGenerationforWeb-services.md
    relatedAPIs:
      - relatedAPI:
        title: Token Access
        description: Token Access
        type: "post"
        path: "/"
  - title: Value your Customers
    description: Create reward programs for your customers and develop Apps to our Clover Marketplace.
    tags: [ "sba-EN-solicitar-token" ]
    bullets: [ "sba-EN-solicitar-token" ]
    relatedDocs:
      - relatedDoc:
        title: APIs - Introduction
        description: APIs - Introduction
        link: ./docs/APIs-Introduction.md
      - relatedDoc:
        title: Token Access
        description: Token Access
        link: ./docs/TokenGenerationforWeb-services.md
    relatedAPIs:
      - relatedAPI:
        title: Token Access
        description: Token Access
        type: "post"
        path: "/"
  - title: Customized Solutions
    description: No matter the nature of your business, we have the ideal integration model.
    tags: [ "sba-EN-solicitar-token" ]
    bullets: [ "sba-EN-solicitar-token" ]
    relatedDocs:
      - relatedDoc:
        title: APIs - Introduction
        description: APIs - Introduction
        link: ./docs/APIs-Introduction.md
      - relatedDoc:
        title: Token Access
        description: Token Access
        link: ./docs/TokenGenerationforWeb-services.md
    relatedAPIs:
      - relatedAPI:
        title: Token Access
        description: Token Access
        type: "post"
        path: "/sba-EN-solicitar-token"
